---
default: true

line-length:
  line_length: 210

no-duplicate-heading:
  siblings_only: true

single-title:
  front_matter_title: ""

no-inline-html:
  allowed_elements:
    - br

descriptive-link-text: false

table:
  style: 'compact'
  aligned_delimiter: true
