#!/usr/bin/env ruby
# frozen_string_literal: true

# Transform Puppet Doc HTML table of contents to VitePress
# nav format:
#
#   https://vuejs.github.io/vitepress/v1/reference/default-theme-sidebar
#
# This script was generated by: Claude Opus 4.6 <noreply@anthropic.com>

require 'rexml/document'
require 'yaml'

# Normalize malformed HTML into well-formed XML by ensuring all <li>
# tags are properly closed. Tracks nesting through <ul> levels using
# a stack.
def normalize_html(html)
  tokens = html.scan(%r{</?\w[^>]*>|[^<]+})
  result = []
  # Stack tracks whether an <li> is currently open at each <ul> depth
  li_stack = []

  tokens.each do |token|
    case token
    when /\A<ul[\s>]/i
      li_stack.push(false)
    when %r{\A</ul>}i
      result << '</li>' if li_stack.last
      li_stack.pop
    when /\A<li[\s>]/i
      result << '</li>' if li_stack.last
      li_stack[-1] = true unless li_stack.empty?
    when %r{\A</li>}i
      li_stack[-1] = false unless li_stack.empty?
    end
    result << token
  end

  result.join
end

def extract_link(href)
  # Strip the /puppetserver/<version>/ prefix, leaving just the relative path.
  # After template variable removal, URLs look like /puppetserver//foo.html
  href.sub(%r{^/puppetserver//}, '')
end

# rubocop:disable Naming/MethodParameterName
def process_li(li)
  a = li.elements['a']
  strong = li.elements['strong']
  ul = li.elements['ul']

  if strong && ul
    group = { 'text' => strong.text.strip, 'items' => [] }
    ul.elements.each('li') do |sub_li|
      item = process_li(sub_li)
      group['items'] << item if item
    end
    group
  elsif a && ul
    items = [{ 'text' => a.text.strip, 'link' => extract_link(a.attributes['href']) }]
    ul.elements.each('li') do |sub_li|
      item = process_li(sub_li)
      items << item if item
    end
    { 'text' => a.text.strip, 'items' => items }
  elsif a
    { 'text' => a.text.strip, 'link' => extract_link(a.attributes['href']) }
  end
end
# rubocop:enable Naming/MethodParameterName

# --- Main ---

input_file = ARGV[0]
abort "Usage: #{$PROGRAM_NAME} <html-toc>" unless input_file

html = File.read(input_file)

# Strip the first line (Liquid capture tag)
html = html.lines.drop(1).join

# Remove Liquid template variables
html = html.gsub(/\{\{\s*\w+\s*\}\}/, '')

# Fix <li> typo used instead of </li>
html = html.gsub(%r{</a><li>}, '</a></li>')

# Normalize to well-formed XML
html = normalize_html(html)

doc = REXML::Document.new("<root>#{html}</root>")

sidebar = []
top_ul = doc.root.elements['ul']

prev_item = nil
top_ul.elements.each do |el|
  case el.name
  when 'li'
    item = process_li(el)
    if item
      sidebar << item
      prev_item = item
    end
  when 'ul'
    # Orphan <ul> — associate with the preceding item as a group
    if prev_item&.key?('link')
      items = [{ 'text' => prev_item['text'], 'link' => prev_item['link'] }]
      el.elements.each('li') do |sub_li|
        sub = process_li(sub_li)
        items << sub if sub
      end
      prev_item.delete('link')
      prev_item['items'] = items
    end
  end
end

puts sidebar.to_yaml
